---
# Specify files or folders which are to be copied
files:
  # Dotfiles
  - src: files/dotfiles/.bash_profile
    dest: ~/.bash_profile
  - src: files/dotfiles/.gitconfig
    dest: ~/.gitconfig
  - src: files/dotfiles/.config/fish/config.fish
    dest: ~/.config/fish/config.fish
  # - src: files/dotfiles/.ipython/profile_default/ipython_config.py
  #   dest: ~/.ipython/profile_default/ipython_config.py

  # # DMG Audio EQuilibrium
  # - src: files/dmgaudio/Default Bank.eqi
  #   dest: ~/Library/Application Support/DMGAudio/EQuilibrium/Default Bank.eqi

  # Software Licenses
  # - src: "{{ cloud_app_license_dir }}/Sublime Text/License.sublime_license"
  #   dest: ~/Library/Application Support/Sublime Text 3/Local/License.sublime_license
  # - src: "{{ cloud_app_license_dir }}/VMware Fusion/license-fusion-80-e3-201505"
  #   dest: /Library/Preferences/VMware Fusion/license-fusion-80-e3-201505

# Specify files which are to be symlinked to others
# symbolic_links:
  # # Audio Hijack cloud storage
  # - src: "{{ cloud_app_config_dir }}/Audio Hijack"
  #   dest: '~/Library/Application Support/Audio Hijack'
  # # OpenEmu cloud storage
  # - src: "{{ cloud_app_config_dir }}/OpenEmu/BIOS"
  #   dest: '~/Library/Application Support/OpenEmu/BIOS'
  # - src: "{{ cloud_app_config_dir }}/OpenEmu/Bindings"
  #   dest: '~/Library/Application Support/OpenEmu/Bindings'
  # - src: "{{ cloud_app_config_dir }}/OpenEmu/Cores"
  #   dest: '~/Library/Application Support/OpenEmu/Cores'
  # - src: "{{ cloud_app_config_dir }}/OpenEmu/Game Library"
  #   dest: '~/Library/Application Support/OpenEmu/Game Library'
  # - src: "{{ cloud_app_config_dir }}/OpenEmu/Save States"
  #   dest: '~/Library/Application Support/OpenEmu/Save States'
