---
# Set various defaults which will update the relevant plist files
osapp_defaults:
  # --- OS X ---
  # Launch Services
  - domain: com.apple.LaunchServices
    values:
      # Disable the 'Are you sure you want to open this application?' dialog
      LSQuarantine: false

  # Login Window
  - domain: com.apple.loginwindow
    values:
      # Disable 'Reopen windows when logging back in' by default
      TALLogoutSavesState: false

  # Dock
  - domain: com.apple.dock
    values:
      # Set the icon size of dock items
      tilesize: 60
      # Enable magnificationn of icons
      magnification: true
      # Make hidden applications translucent in the dock
      showhidden: true

  # Finder
  - domain: com.apple.finder
    values:
      # View / Show Status Bar
      ShowStatusBar: true
      # Set the default Finder display mode to list
      FXPreferredViewStyle: Nlsv

  # Menu (Clock)
  - domain: com.apple.menuextra.clock
    values:
      # Open Date & Time Preferences... / Clock / Show date
      DateFormat: "EEE d MMM  h:mm a"

  # --- Apple Software ---
  # Safari
  - domain: com.apple.Safari
    values:
      # View / Show Status Bar
      ShowStatusBar: true
